apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: my-pod
    type: proxy
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
# minikube start (starts)
# kubectl create -f pod.yaml (Create)
# kubectl get pods   (Show)
# kubectl delete pod nginx (Deleted)
