apiVersion: v1
kind: Service
metadata:
  name: broken-service
spec:
  selector:
    app: web-app #WAS WRONG THE SELECTOR WAS broken-app and the template was searching for web-app
  ports:
    - port: 80
      targetPort: 80 #the target was also wrong, was not 8080 but 80
  type: NodePort
